#!/bin/bash

DIR="${1:-.}"
DEFAULT="fex_"$(date +%Y_%m_%d)".csv"
OUT="${2:-$DEFAULT}"

for f in $(find $DIR -regex '.*\.\(wav\|WAV\)'); do
	NAME="${f%.*}"
	NAME="${NAME#*/}"
	FE=$(fex $f)
	echo -e "$NAME\t$FE" >> "${OUT}"
done
