#!/bin/bash

IFS="|"
# select file(s)
filelist=( $(zenity \
		--title "FEX: Frequency Excursion Calculator" \
		--file-selection --multiple --separator="|") )
nfiles=${#filelist[@]}

# create a temporary data file
out="$(mktemp fex.XXXXXX)"
echo -e "Song\tF.E." > "$out"

# loop through selected files
for file in ${filelist[@]}; do
	song_file="$(basename $file)"
	song_name="${song%.*}"
	fe="$(fex "$file")"
	# if only one file, display result in dialog
	if [[ $nfiles -eq 1 ]]; then
		zenity --text-info --title "FEX: $song" --text  "F.E. = $fe"
	# else write to the data file
	else
		echo -e "$song_name\t$fe" >> $out
	fi
done

if [[ $nfiles -gt 1 ]]; then
	data="$(zenity --title "FEX: save data file" \
			--file-selection --save --confirm-overwrite)"
	[[ -n $data ]] && cp "$out" "$data"
else
	rm -f $out
fi
