#!/bin/bash

## VERSION:
#V#MakeDEB
#V#  version 1.0, copyright 2014, Jesse McClure
#V#  license: CC-BY-SA https://creativecommons.org/licenses/by-sa/2.0/
## HELP:

if [[ -n $1 ]]; then
	case $1 in
		-h|--help|help) awk '/^#[VH]#/ { sub(/^#[VH]#/,""); print $0; }' $0 ;;
		-v|--ver*|ver*) awk '/^#V#/ { sub(/^#V#/,""); print $0; }' $0 ;;
	esac
	exit
fi

start_dir=$(pwd)

spec=$(find  -maxdepth 1 -name "*.spec")
if [[ ! -f ${spec} ]]; then
	echo "No spec file found"
	exit 1
fi

## GET VALUES FROM SPEC FILE:
pkgbase=$(awk -F ': ' '/^name:/ { print $2; }' ${spec})
pkgname=$(basename ${spec})
pkgname=${pkgname/\.spec/}
git_url=$(awk -F ': ' '/^source:/ { print $2; }' ${spec})
pkgver_base=$(awk -F ': ' '/^version:/ { print $2; }' ${spec})
email=$(awk -F ': ' '/^packager:/ { print $2; }' ${spec})
license=$(awk -F ': ' '/^license:/ { print $2; }' ${spec})
upstream_url=$(awk -F ': ' '/^url:/ { print $2; }' ${spec})
description=$(awk -F ': ' '/^summary:/ { print $2; }' ${spec})
section=$(awk -F ': ' '/^group:/ { print $2; }' ${spec})
build_deps=$(awk -F ': ' '/^buildrequires:/ { print $2; }' ${spec})
deps=$(awk -F ': ' '/^requires:/ { print $2; }' ${spec})

## CHECK BUILD ENVIRONMENT:
#sudo apt-get install build-essential autoconf automake autotools-dev dh-make debhelper devscripts fakeroot xutils lintian pbuilder
topdir=/tmp/makeDEB
rm -rf ${topdir}/${pkgname}
mkdir -p ${topdir}/${pkgname}

## GET CODE AND MAKE SOURCE TARBALL:
if [[ -d ${pkgname} ]]; then
	cd ${pkgname};
	git pull;
else
	git clone ${git_url} ${pkgname}
	cd ${pkgname}
fi
pkgver="${pkgver_base}.$(git rev-list --count HEAD)"
make dist
mv ${pkgbase}*.tar.gz ${topdir}/${pkgname}/${pkgname}-${pkgver}.tar.gz

## BUILD FOLDER PREPARATION
cd ${start_dir}
mv ${pkgname} ${topdir}/${pkgname}/${pkgname}-${pkgver}

## DEBIANIZE
cd ${topdir}/${pkgname}/${pkgname}-${pkgver}
dh_make													\
	--copyright "${license}"						\
	--email "${email}"								\
	--file "../${pkgname}-${pkgver}.tar.gz"	\
	--single												\
	--yes

## EDIT CONTROL FILE
sed -i 's|^Depends:.*|Depends: '"${deps}"'|' debian/control
sed -i 's|^Build-Depends:.*|Build-Depends: '"${build_deps}"'|' debian/control
sed -i 's|^Maintainer:.*|Maintainer: '"${email}"'|' debian/control
sed -i 's|^Homepage:.*|Homepage: '"${upstream_url}"'|' debian/control
sed -i 's|^Description:.*|Description: '"${description}"'|' debian/control
sed -i 's|^Section:.*|Section: '"${section}"'|' debian/control

## CREATE CHANGELOG
#echo "${pkgname} (${pkgver}-1) unstable; urgency=low" > debian/changelog
#echo "* Initial release" >> debian/changelog
#echo "-- ${maintainer} <${email}> " >> debian/changelog

## BUILD THE PACKAGE
dpkg-buildpackage

## CLEAN UP:
cd ${startdir}

