#!/usr/bin/env python2
#----------------------------------------------------------------------#
# FEX - The Frequency Excursion Calculator
#
# Author: Jesse McClure, copyright 2013-2014
# License: GPL3
#
#    This program is free software: you can redistribute it and/or
#    modify it under the terms of the GNU General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see
#    <http://www.gnu.org/licenses/>.
#
#----------------------------------------------------------------------#

import sys
import os
import subprocess
import pygtk
import gtk

def main(argv):
	if (len(argv) == 0):
		filelist = input_files()
	else:
		filelist = argv
	if (len(filelist) == 0):
		sys.exit(0)
	data = "Song\tFEX\n"
	for filename in filelist:
		song = os.path.splitext(os.path.basename(filename))[0]
		try:
			FE = subprocess.check_output(["fex",filename])
		except subprocess.CalledProcessError as err:
			FE = "NA\n"
		data = data + song + "\t" + FE
	if (len(filelist) == 1):
		filename = ""
	else:
		filename = data_file()
	if (len(filename) == 0):
		label = gtk.Label(data)
		win = gtk.Dialog("Fex", None,
				gtk.DIALOG_DESTROY_WITH_PARENT,
				(gtk.STOCK_OK, gtk.RESPONSE_ACCEPT))
		win.vbox.pack_start(label)
		label.show()
		win.run()
	else:
		fptr = open(filename,"w")
		fptr.write(data)

def input_files():
	win = gtk.FileChooserDialog("Open ...", None,
			gtk.FILE_CHOOSER_ACTION_OPEN,
			(gtk.STOCK_CANCEL, gtk.RESPONSE_CANCEL,
			gtk.STOCK_OPEN, gtk.RESPONSE_OK))
	win.set_default_response(gtk.RESPONSE_OK)
	win.set_select_multiple(True)
	# wave filter
	filter = gtk.FileFilter()
	filter.set_name("Waves")
	filter.add_pattern("*.wav")
	filter.add_pattern("*.WAV")
	win.add_filter(filter)
	# alternative filter
	filter = gtk.FileFilter()
	filter.set_name("All files")
	filter.add_pattern("*")
	win.add_filter(filter)
	# get files
	response = win.run()
	if (response == gtk.RESPONSE_OK):
		filelist = win.get_filenames()
	else:
		filelist = []
	win.destroy()
	while gtk.events_pending():
	   gtk.main_iteration(False)
	return filelist

def data_file():
	win = gtk.FileChooserDialog("Save As ...", None,
			gtk.FILE_CHOOSER_ACTION_SAVE,
			(gtk.STOCK_CANCEL, gtk.RESPONSE_CANCEL,
			gtk.STOCK_OPEN, gtk.RESPONSE_OK))
	win.set_default_response(gtk.RESPONSE_OK)
	win.set_do_overwrite_confirmation(True);
	response = win.run()
	if (response == gtk.RESPONSE_OK):
		filename = win.get_filename()
	else:
		filename = ""
	win.destroy()
	return filename

if (__name__ == "__main__"):
	main(sys.argv[1:])

